/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package util;

import org.junit.Test;
import static org.junit.Assert.*;

public class StringCipherTest {

    /**
     * 
     */
    @Test
    public void testEncrypAndDecrypt() {
        StringCipher cipher = new StringCipher("iS5KfTPfn4xLjYYy", "ncfeKKfPYedi9hJs");
        String encrypted = cipher.encrypt("english-日本語");
        String decrypted = cipher.decrypt(encrypted);
        System.out.println(encrypted);
        System.out.println(decrypted);
        assertEquals(decrypted, "english-日本語");
    }
}
